### ISSUE TITLE
Add reCaptcha as a field option

### ISSUE THREAD

**Issue by jjanssen** [LUKKIEN/wagtailformblocks#3]
In addition to the field type it would be nice if we have a reCaptcha option when this app is available within the `INSTALLED_APPS` list.

**Comment by OktayAltay** [comment]
I am gonna get started on this isse. By implementing the following package: https://github.com/praekelt/django-recaptcha

**Comment by Henk-JanVanHasselaar** [comment]
@OktayAltay Cool, can you add a ratelimiter too? so the recaptcha will only show after X number of submits?  maybe:http://django-ratelimit.readthedocs.io/en/latest/

**Comment by jjanssen** [comment]
@Henk-JanVanHasselaar lets make a seperate issue out of this one. Recaptcha is has the priority at this moment due to project commitments.

**Comment by Henk-JanVanHasselaar** [comment]
Sure, ref in issue #8

**Comment by mikedingjan** [comment]
IMHO this is something we should tackle together...

**Comment by mikedingjan** [comment]
Field option is not possible, we're going for a checkbox on the form itself.

**Comment by jjanssen** [comment]
Fixed in 0.1.3
